/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package launcher;

import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import model.RutaHome;
import org.json.JSONException;
import utilidades.LectorRutaHome;
import utilidades.Utility;

/**
 *
 * @author sergio
 */
public class principal extends javax.swing.JFrame {

    private VistaHome vistaHome;
    private VistaGame vistaGame;
    private Utility utilidades;
    private LectorRutaHome rutasHome;

    /**
     * Creates new form principal
     */
    public principal() throws JSONException, URISyntaxException {
        this.utilidades = new Utility();
        LectorRutaHome rutasHome = new LectorRutaHome();
        this.rutasHome = rutasHome;
        this.vistaHome = new VistaHome();
        this.vistaGame = new VistaGame();
        //utilidades.leerEstadistica(5);
        initComponents();
        write();
        //utilidades.escribirEstadistica(5);

    }

    public void write() {
        Boolean writeNow = false;
        utilidades.slowPrint(jTextArea1, "Cada escudo es un grado\ncada grado tiene 6 juegos.\nParticipa en este reto de ingenio y sabiduría...\n¿Te atreves?\n\nPulsa en la barra superior el ciclo.");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        FondoP = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        launcherBtn0 = new javax.swing.JButton();
        launcherBtn1 = new javax.swing.JButton();
        launcherBtn2 = new javax.swing.JButton();
        launcherBtn3 = new javax.swing.JButton();
        launcherBtn4 = new javax.swing.JButton();
        launcherBtn5 = new javax.swing.JButton();
        launcherBtn6 = new javax.swing.JButton();
        launcherBtn7 = new javax.swing.JButton();
        launcherBtn8 = new javax.swing.JButton();
        launcherBtn9 = new javax.swing.JButton();
        launcherBtn10 = new javax.swing.JButton();
        launcherBtn11 = new javax.swing.JButton();
        launcherBtn12 = new javax.swing.JButton();
        launcherBtn13 = new javax.swing.JButton();
        cuerpoPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextTitulo = new javax.swing.JTextArea();
        tituloGradoJL = new javax.swing.JLabel();
        barritaJL = new javax.swing.JLabel();
        FacebookBtn1 = new javax.swing.JButton();
        IstagramBtn = new javax.swing.JButton();
        YoutubeBtn = new javax.swing.JButton();
        TwichBtn = new javax.swing.JButton();
        LinkedinBtn = new javax.swing.JButton();
        TiktokBtn = new javax.swing.JButton();
        Xbtn = new javax.swing.JButton();
        GoogleBtn = new javax.swing.JButton();
        FondoJL = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setUndecorated(true);

        FondoP.setBackground(new java.awt.Color(255, 255, 255));
        FondoP.setMaximumSize(new java.awt.Dimension(1540, 850));
        FondoP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        launcherBtn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton0.png"))); // NOI18N
        launcherBtn0.setToolTipText("HOME");
        launcherBtn0.setContentAreaFilled(false);
        launcherBtn0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        launcherBtn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton0.png"))); // NOI18N
        launcherBtn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/launcheBtn00.png"))); // NOI18N
        launcherBtn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn0MouseEntered(evt);
            }
        });
        launcherBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launcherBtn0ActionPerformed(evt);
            }
        });

        launcherBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton1.png"))); // NOI18N
        launcherBtn1.setToolTipText("");
        launcherBtn1.setContentAreaFilled(false);
        launcherBtn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton1.png"))); // NOI18N
        launcherBtn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn1.png"))); // NOI18N
        launcherBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                launcherBtn1MousePressed(evt);
            }
        });

        launcherBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton2.png"))); // NOI18N
        launcherBtn2.setContentAreaFilled(false);
        launcherBtn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton2.png"))); // NOI18N
        launcherBtn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn2.png"))); // NOI18N
        launcherBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn2MouseEntered(evt);
            }
        });

        launcherBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton3.png"))); // NOI18N
        launcherBtn3.setContentAreaFilled(false);
        launcherBtn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton3.png"))); // NOI18N
        launcherBtn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn3.png"))); // NOI18N
        launcherBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn3MouseEntered(evt);
            }
        });

        launcherBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton4.png"))); // NOI18N
        launcherBtn4.setContentAreaFilled(false);
        launcherBtn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton4.png"))); // NOI18N
        launcherBtn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn4.png"))); // NOI18N
        launcherBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn4MouseEntered(evt);
            }
        });

        launcherBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton5.png"))); // NOI18N
        launcherBtn5.setContentAreaFilled(false);
        launcherBtn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton5.png"))); // NOI18N
        launcherBtn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn5.png"))); // NOI18N
        launcherBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn5MouseEntered(evt);
            }
        });

        launcherBtn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton6.png"))); // NOI18N
        launcherBtn6.setContentAreaFilled(false);
        launcherBtn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton6.png"))); // NOI18N
        launcherBtn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn6.png"))); // NOI18N
        launcherBtn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn6MouseEntered(evt);
            }
        });

        launcherBtn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton7.png"))); // NOI18N
        launcherBtn7.setToolTipText("");
        launcherBtn7.setContentAreaFilled(false);
        launcherBtn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton7.png"))); // NOI18N
        launcherBtn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn7.png"))); // NOI18N
        launcherBtn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn7MouseEntered(evt);
            }
        });

        launcherBtn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton8.png"))); // NOI18N
        launcherBtn8.setContentAreaFilled(false);
        launcherBtn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton8.png"))); // NOI18N
        launcherBtn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn8.png"))); // NOI18N
        launcherBtn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn8MouseEntered(evt);
            }
        });

        launcherBtn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton9.png"))); // NOI18N
        launcherBtn9.setToolTipText("");
        launcherBtn9.setContentAreaFilled(false);
        launcherBtn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton9.png"))); // NOI18N
        launcherBtn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn9.png"))); // NOI18N
        launcherBtn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn9MouseEntered(evt);
            }
        });

        launcherBtn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton10.png"))); // NOI18N
        launcherBtn10.setContentAreaFilled(false);
        launcherBtn10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton10.png"))); // NOI18N
        launcherBtn10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn10.png"))); // NOI18N
        launcherBtn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn10MouseEntered(evt);
            }
        });

        launcherBtn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton11.png"))); // NOI18N
        launcherBtn11.setContentAreaFilled(false);
        launcherBtn11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton11.png"))); // NOI18N
        launcherBtn11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn11.png"))); // NOI18N
        launcherBtn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn11MouseEntered(evt);
            }
        });

        launcherBtn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton12.png"))); // NOI18N
        launcherBtn12.setContentAreaFilled(false);
        launcherBtn12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton12.png"))); // NOI18N
        launcherBtn12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn12.png"))); // NOI18N
        launcherBtn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn12MouseEntered(evt);
            }
        });

        launcherBtn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton13.png"))); // NOI18N
        launcherBtn13.setContentAreaFilled(false);
        launcherBtn13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton13.png"))); // NOI18N
        launcherBtn13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherBtn13.png"))); // NOI18N
        launcherBtn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                launcherBtn3Mouse(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(launcherBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherBtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(launcherBtn0, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(launcherBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(launcherBtn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        FondoP.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 1560, 170));

        cuerpoPrincipal.setBackground(new java.awt.Color(10, 38, 72));
        cuerpoPrincipal.setMaximumSize(new java.awt.Dimension(1540, 850));
        cuerpoPrincipal.setMinimumSize(new java.awt.Dimension(1540, 850));
        cuerpoPrincipal.setPreferredSize(new java.awt.Dimension(1540, 850));

        jScrollPane1.setBackground(new java.awt.Color(10, 38, 72));
        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(10, 38, 72));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(10, 38, 72));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setCaretColor(new java.awt.Color(10, 38, 72));
        jTextArea1.setDisabledTextColor(new java.awt.Color(10, 38, 72));
        jTextArea1.setFocusable(false);
        jTextArea1.setSelectedTextColor(new java.awt.Color(10, 38, 72));
        jTextArea1.setSelectionColor(new java.awt.Color(10, 38, 72));
        jTextArea1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setOpaque(false);

        jTextTitulo.setEditable(false);
        jTextTitulo.setBackground(new java.awt.Color(10, 38, 72));
        jTextTitulo.setColumns(20);
        jTextTitulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jTextTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTextTitulo.setRows(5);
        jTextTitulo.setText("14 Grados diferentes a elegir");
        jTextTitulo.setToolTipText("14 Grados diferentes a elegir");
        jTextTitulo.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextTitulo);

        tituloGradoJL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoUniversae.png"))); // NOI18N
        tituloGradoJL.setText("jLabel5");

        barritaJL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Barrita aislada descripción.png"))); // NOI18N

        javax.swing.GroupLayout cuerpoPrincipalLayout = new javax.swing.GroupLayout(cuerpoPrincipal);
        cuerpoPrincipal.setLayout(cuerpoPrincipalLayout);
        cuerpoPrincipalLayout.setHorizontalGroup(
            cuerpoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuerpoPrincipalLayout.createSequentialGroup()
                .addGroup(cuerpoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuerpoPrincipalLayout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cuerpoPrincipalLayout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(tituloGradoJL, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cuerpoPrincipalLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(barritaJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        cuerpoPrincipalLayout.setVerticalGroup(
            cuerpoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuerpoPrincipalLayout.createSequentialGroup()
                .addGroup(cuerpoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuerpoPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(barritaJL))
                    .addGroup(cuerpoPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(tituloGradoJL, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        FondoP.add(cuerpoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 1550, 860));

        FacebookBtn1.setBorder(null);
        FacebookBtn1.setContentAreaFilled(false);
        FacebookBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FacebookBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacebookBtn1MouseClicked(evt);
            }
        });
        FondoP.add(FacebookBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 170, 40));

        IstagramBtn.setToolTipText("");
        IstagramBtn.setBorder(null);
        IstagramBtn.setContentAreaFilled(false);
        IstagramBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IstagramBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IstagramBtnMouseClicked(evt);
            }
        });
        FondoP.add(IstagramBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, 30));

        YoutubeBtn.setToolTipText("");
        YoutubeBtn.setBorder(null);
        YoutubeBtn.setContentAreaFilled(false);
        YoutubeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        YoutubeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YoutubeBtnMouseClicked(evt);
            }
        });
        FondoP.add(YoutubeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 30));

        TwichBtn.setBorder(null);
        TwichBtn.setContentAreaFilled(false);
        TwichBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TwichBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TwichBtnMouseClicked(evt);
            }
        });
        FondoP.add(TwichBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, 40));

        LinkedinBtn.setBorder(null);
        LinkedinBtn.setContentAreaFilled(false);
        LinkedinBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LinkedinBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LinkedinBtnMouseClicked(evt);
            }
        });
        FondoP.add(LinkedinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 160, 40));

        TiktokBtn.setBorder(null);
        TiktokBtn.setContentAreaFilled(false);
        TiktokBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TiktokBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TiktokBtnMouseClicked(evt);
            }
        });
        FondoP.add(TiktokBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 160, 40));

        Xbtn.setBorder(null);
        Xbtn.setContentAreaFilled(false);
        Xbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Xbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XbtnMouseClicked(evt);
            }
        });
        FondoP.add(Xbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 170, 30));

        GoogleBtn.setBorder(null);
        GoogleBtn.setContentAreaFilled(false);
        GoogleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoogleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoogleBtnMouseClicked(evt);
            }
        });
        FondoP.add(GoogleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 220, 30));

        FondoJL.setBackground(new java.awt.Color(10, 38, 72));
        FondoJL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoBase.png"))); // NOI18N
        FondoJL.setText("jLabel1");
        FondoJL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FondoP.add(FondoJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));
        FondoJL.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FondoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launcherBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launcherBtn0ActionPerformed
        jTextTitulo.setText("16 Grados diferentes a elegir");

        //Sonido al seleccionar el ratón
        Clip sound = utilidades.getSound("seleccionar.wav");
        // Esta acción lleva a la Vista Home
        vistaHome.borrarTransparente();

        // Se queda el escudo en Grande
        launcherBtn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/launcheBtn00.png")));
        utilidades.showPanel(cuerpoPrincipal, vistaHome);

        try {
            vistaHome.mostrarHome(0);
        } catch (JSONException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_launcherBtn0ActionPerformed

    public String nombreGrado(int numero) throws JSONException {
        ArrayList<RutaHome> rutas = rutasHome.jsonArray();

        String titulo = rutas.get(numero).getNombre();
        return titulo;
    }

    private void launcherBtn0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn0MouseEntered
        //texto emergente
        String texto = "Grado 1";

        launcherBtn0.setToolTipText(texto);

        //Sonido al pasar el ratón
        String titulo = "Grado";
        // Quita el botón grande una vez seleccionado
        launcherBtn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesIconos/LauncherButton0.png")));
        try {
            titulo = nombreGrado(0);
        } catch (JSONException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextTitulo.setText(titulo);
        Clip sound = utilidades.getSound("pasar.wav");
    }//GEN-LAST:event_launcherBtn0MouseEntered

    private void launcherBtn3Mouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn3Mouse
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");
    }//GEN-LAST:event_launcherBtn3Mouse

    private void launcherBtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn1MousePressed
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

    }//GEN-LAST:event_launcherBtn1MousePressed

    private void launcherBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn1MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");
        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn1.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn1MouseEntered

    private void launcherBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn2MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn2.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn2MouseEntered

    private void launcherBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn3MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn3.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn3MouseEntered

    private void launcherBtn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn4MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn4.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn4MouseEntered

    private void launcherBtn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn5MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn5.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn5MouseEntered

    private void launcherBtn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn6MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn6.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn6MouseEntered

    private void launcherBtn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn7MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn7.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn7MouseEntered

    private void launcherBtn8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn8MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn8.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn8MouseEntered

    private void launcherBtn9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn9MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn9.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn9MouseEntered

    private void launcherBtn10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn10MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "Este boton hace....";

        launcherBtn10.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn10MouseEntered

    private void FacebookBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacebookBtn1MouseClicked
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.BROWSE)) {
                try {
                    URI uri = new URI("https://www.facebook.com/UNIVERSAE/");
                    desktop.browse(uri);

                } catch (Exception ignored) {
                }
            }
    }//GEN-LAST:event_FacebookBtn1MouseClicked
    }
    private void IstagramBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IstagramBtnMouseClicked
        // Comprobar si Desktop es soportado por la plataforma
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            // Comprobar si la acción BROWSE es soportada
            if (desktop.isSupported(Desktop.Action.BROWSE)) {
                try {
                    // Definir la URI de Facebook
                    URI uri = new URI("https://www.instagram.com/_universae/");
                    // Abrir la URI en el navegador predeterminado
                    desktop.browse(uri);
                    // En este caso, estamos ignorando las excepciones.
                } catch (Exception ignored) {
                }
            }
        }
    }//GEN-LAST:event_IstagramBtnMouseClicked

    private void YoutubeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YoutubeBtnMouseClicked
        // Comprobar si Desktop es soportado por la plataforma
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            // Comprobar si la acción BROWSE es soportada
            if (desktop.isSupported(Desktop.Action.BROWSE)) {
                try {
                    // Definir la URI de Facebook
                    URI uri = new URI("https://www.youtube.com/c/UNIVERSAE_FP");
                    // Abrir la URI en el navegador predeterminado
                    desktop.browse(uri);
                    // En este caso, estamos ignorando las excepciones.
                } catch (Exception ignored) {
                }
            }
        }
    }//GEN-LAST:event_YoutubeBtnMouseClicked

    private void TwichBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwichBtnMouseClicked
        // Comprobar si Desktop es soportado por la plataforma
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            // Comprobar si la acción BROWSE es soportada
            if (desktop.isSupported(Desktop.Action.BROWSE)) {
                try {
                    // Definir la URI de Facebook
                    URI uri = new URI("https://www.twitch.tv/universae_fp");
                    // Abrir la URI en el navegador predeterminado
                    desktop.browse(uri);
                    // En este caso, estamos ignorando las excepciones.    
                } catch (Exception ignored) {
                }
            }
        }
    }//GEN-LAST:event_TwichBtnMouseClicked

    private void LinkedinBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinkedinBtnMouseClicked
        // Comprobar si Desktop es soportado por la plataforma
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            // Comprobar si la acción BROWSE es soportada
            if (desktop.isSupported(Desktop.Action.BROWSE)) {
                try {
                    // Definir la URI de Facebook
                    URI uri = new URI("https://es.linkedin.com/school/universae/");
                    // Abrir la URI en el navegador predeterminado
                    desktop.browse(uri);
                    // En este caso, estamos ignorando las excepciones.    
                } catch (Exception ignored) {
                }
            }
        }
    }//GEN-LAST:event_LinkedinBtnMouseClicked

    private void TiktokBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TiktokBtnMouseClicked
        // Comprobar si Desktop es soportado por la plataforma
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            // Comprobar si la acción BROWSE es soportada
            if (desktop.isSupported(Desktop.Action.BROWSE)) {
                try {
                    // Definir la URI de Facebook
                    URI uri = new URI("https://www.tiktok.com/@_universae");
                    // Abrir la URI en el navegador predeterminado
                    desktop.browse(uri);
                    // En este caso, estamos ignorando las excepciones.    
                } catch (Exception ignored) {
                }
            }
        }
    }//GEN-LAST:event_TiktokBtnMouseClicked

    private void XbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XbtnMouseClicked
        // Comprobar si Desktop es soportado por la plataforma
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            // Comprobar si la acción BROWSE es soportada
            if (desktop.isSupported(Desktop.Action.BROWSE)) {
                try {
                    // Definir la URI de Facebook
                    URI uri = new URI("https://twitter.com/_Universae/");
                    // Abrir la URI en el navegador predeterminado
                    desktop.browse(uri);
                    // En este caso, estamos ignorando las excepciones.    
                } catch (Exception ignored) {
                }
            }
        }
    }//GEN-LAST:event_XbtnMouseClicked

    private void GoogleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoogleBtnMouseClicked
        // Comprobar si Desktop es soportado por la plataforma
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            // Comprobar si la acción BROWSE es soportada
            if (desktop.isSupported(Desktop.Action.BROWSE)) {
                try {
                    // Definir la URI de Facebook
                    URI uri = new URI("https://universae.com/");
                    // Abrir la URI en el navegador predeterminado
                    desktop.browse(uri);
                    // En este caso, estamos ignorando las excepciones.    
                } catch (Exception ignored) {
                }
            }
        }
    }//GEN-LAST:event_GoogleBtnMouseClicked

    private void launcherBtn12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn12MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "HOME";
        launcherBtn0.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn12MouseEntered

    private void launcherBtn11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launcherBtn11MouseEntered
        //Sonido al pasar el ratón
        Clip sound = utilidades.getSound("pasar.wav");

        //texto emergente
        String texto = "HOME";
        launcherBtn0.setToolTipText(texto);
    }//GEN-LAST:event_launcherBtn11MouseEntered

    public void launcherGame(int game) {

        utilidades.showPanel(cuerpoPrincipal, vistaGame);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new principal().setVisible(true);
                } catch (JSONException ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FacebookBtn1;
    private javax.swing.JLabel FondoJL;
    public static javax.swing.JPanel FondoP;
    private javax.swing.JButton GoogleBtn;
    private javax.swing.JButton IstagramBtn;
    private javax.swing.JButton LinkedinBtn;
    private javax.swing.JButton TiktokBtn;
    private javax.swing.JButton TwichBtn;
    private javax.swing.JButton Xbtn;
    private javax.swing.JButton YoutubeBtn;
    private javax.swing.JLabel barritaJL;
    private javax.swing.JPanel cuerpoPrincipal;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextTitulo;
    private javax.swing.JButton launcherBtn0;
    private javax.swing.JButton launcherBtn1;
    private javax.swing.JButton launcherBtn10;
    private javax.swing.JButton launcherBtn11;
    private javax.swing.JButton launcherBtn12;
    private javax.swing.JButton launcherBtn13;
    private javax.swing.JButton launcherBtn2;
    private javax.swing.JButton launcherBtn3;
    private javax.swing.JButton launcherBtn4;
    private javax.swing.JButton launcherBtn5;
    private javax.swing.JButton launcherBtn6;
    private javax.swing.JButton launcherBtn7;
    private javax.swing.JButton launcherBtn8;
    private javax.swing.JButton launcherBtn9;
    private javax.swing.JLabel tituloGradoJL;
    // End of variables declaration//GEN-END:variables
}
