/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package launcher;

import javax.swing.ImageIcon;
import utilidades.Utility;

/**
 *
 * @author sergio
 */
public class VistaGameJP extends javax.swing.JPanel {

    // int x = 0;
    /**
     * Creates new form VistaGameJP2
     */
    public VistaGameJP() {
        initComponents();
        String imagenFondoImg = "src/imagenes/interfazGame/fondoImagen.png";

        String imagenPrincipalImg = "src/imagenes/interfazGame/Miniaturas/Helicoptero/Helicoptero0.png";

        Utility utilidades = new Utility();
        imagenFondo.setSize(1050, 430);

        utilidades.SetImageLabel(imagenFondo, imagenFondoImg);

        this.repaint();
        
        
        //Inicializar bolitas
        colocarBolitas();
        colocarBolitaLlena();
        
        
    
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuerpoGame = new javax.swing.JPanel();
        imagenPrincipal = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();
        flechaIzquierda = new javax.swing.JLabel();
        flechaDerecha = new javax.swing.JLabel();
        BolitasPanel = new javax.swing.JPanel();
        bolita1 = new javax.swing.JLabel();
        bolita2 = new javax.swing.JLabel();
        bolita3 = new javax.swing.JLabel();
        bolita4 = new javax.swing.JLabel();
        bolita5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(10, 38, 72));
        setMaximumSize(new java.awt.Dimension(1540, 850));
        setMinimumSize(new java.awt.Dimension(1540, 850));
        setPreferredSize(new java.awt.Dimension(1540, 850));

        cuerpoGame.setBackground(new java.awt.Color(10, 38, 72));
        cuerpoGame.setMaximumSize(new java.awt.Dimension(720, 450));
        cuerpoGame.setMinimumSize(new java.awt.Dimension(1540, 850));
        cuerpoGame.setPreferredSize(new java.awt.Dimension(1540, 850));
        cuerpoGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Miniaturas/Helicoptero/Helicoptero0.png"))); // NOI18N
        imagenPrincipal.setText("0");
        cuerpoGame.add(imagenPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 890, 500));

        imagenFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/fondoImagen.png"))); // NOI18N
        imagenFondo.setMaximumSize(new java.awt.Dimension(1050, 430));
        imagenFondo.setMinimumSize(new java.awt.Dimension(1050, 430));
        imagenFondo.setPreferredSize(new java.awt.Dimension(1050, 430));
        cuerpoGame.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        flechaIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Flecha izquierda.png"))); // NOI18N
        flechaIzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaIzquierdaMouseClicked(evt);
            }
        });
        cuerpoGame.add(flechaIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        flechaDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Flecha derecha.png"))); // NOI18N
        flechaDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaDerechaMouseClicked(evt);
            }
        });
        cuerpoGame.add(flechaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 300, 40, -1));

        BolitasPanel.setBackground(new java.awt.Color(10, 38, 72));

        bolita1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        bolita2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        bolita3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        bolita4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        bolita5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        javax.swing.GroupLayout BolitasPanelLayout = new javax.swing.GroupLayout(BolitasPanel);
        BolitasPanel.setLayout(BolitasPanelLayout);
        BolitasPanelLayout.setHorizontalGroup(
            BolitasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BolitasPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(bolita1)
                .addGap(18, 18, 18)
                .addComponent(bolita2)
                .addGap(18, 18, 18)
                .addComponent(bolita3)
                .addGap(18, 18, 18)
                .addComponent(bolita4)
                .addGap(18, 18, 18)
                .addComponent(bolita5)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        BolitasPanelLayout.setVerticalGroup(
            BolitasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BolitasPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(BolitasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bolita1)
                    .addComponent(bolita2)
                    .addComponent(bolita3)
                    .addComponent(bolita4)
                    .addComponent(bolita5))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        cuerpoGame.add(BolitasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 320, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuerpoGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuerpoGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void flechaDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaDerechaMouseClicked
        setLayout(null);
        // Añadimos el número de imagen en la etiqueta text y recuperamos para sumarle 1, hasta 4
        int x = Integer.parseInt(imagenPrincipal.getText());
        x = x + 1;
        if (x == 5) {
            x = 0;
        }
        // Añadimos numero de imagen y se van cambiando.
        String imagenPrincipalImg = "src/imagenes/interfazGame/Miniaturas/Helicoptero/Helicoptero" + x + ".png";
        imagenPrincipal.setText(String.valueOf(x));
        ImageIcon image = new ImageIcon(imagenPrincipalImg);
        imagenPrincipal.setIcon(image);
        colocarBolitaLlena();
    }//GEN-LAST:event_flechaDerechaMouseClicked

    // Carrusel izquierda
    private void flechaIzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaIzquierdaMouseClicked
        setLayout(null);
        // Añadimos el número de imagen en la etiqueta text y recuperamos para sumarle 1, hasta 4
        int x = Integer.parseInt(imagenPrincipal.getText());
        if (x <= 0) {
            x = 5;
        }
        x = x - 1;
        // Añadimos numero de imagen y se van cambiando.
        String imagenPrincipalImg = "src/imagenes/interfazGame/Miniaturas/Helicoptero/Helicoptero" + x + ".png";
        imagenPrincipal.setText(String.valueOf(x));
        ImageIcon image = new ImageIcon(imagenPrincipalImg);
        imagenPrincipal.setIcon(image);
        colocarBolitaLlena();
    }//GEN-LAST:event_flechaIzquierdaMouseClicked

    //Método para bolitas llenas
    public void colocarBolitaLlena(){
        colocarBolitas();
         String imagenBolitaLlena = "src/imagenes/interfazGame/PuntoCarruselFilled.png";
        ImageIcon image2 = new ImageIcon(imagenBolitaLlena);
        
      int x = Integer.parseInt(imagenPrincipal.getText());
      
      switch (x){
          case 0: 
              bolita1.setIcon(image2);
              break;
          case 1: 
              bolita2.setIcon(image2);
              break;
          case 2: 
              bolita3.setIcon(image2);
              break;
          case 3: 
              bolita4.setIcon(image2);
              break;
          case 4: 
              bolita5.setIcon(image2);
              break;
         
          
          
          
      }
    }
      
      //Método para bolitas vacías
      
     public void colocarBolitas(){
      String imagenBolitaVacia = "src/imagenes/interfazGame/PuntoCarruselEmpty.png";
       
        
        ImageIcon image = new ImageIcon(imagenBolitaVacia);
        bolita1.setIcon(image);
        bolita2.setIcon(image);
        bolita3.setIcon(image);
        bolita4.setIcon(image);
        bolita5.setIcon(image);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BolitasPanel;
    private javax.swing.JLabel bolita1;
    private javax.swing.JLabel bolita2;
    private javax.swing.JLabel bolita3;
    private javax.swing.JLabel bolita4;
    private javax.swing.JLabel bolita5;
    private javax.swing.JPanel cuerpoGame;
    private javax.swing.JLabel flechaDerecha;
    private javax.swing.JLabel flechaIzquierda;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel imagenPrincipal;
    // End of variables declaration//GEN-END:variables
}
