/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package launcher;

import utilidades.Utility;

/**
 *
 * @author sergio
 */
public class VistaGameJP extends javax.swing.JFrame {

    Utility utilidades = new Utility();

    /**
     * Creates new form NewJFrame
     */
    public VistaGameJP() {
        initComponents();
        //this.setLocationRelativeTo(this);
        utilidades.SetImageLabel(ImagenFondo, "src/imagenes/interfazGame/fondoImagen.png");
        utilidades.SetImageLabel(imagenPrincipal, "src/imagenes/interfazGame/Miniaturas/Helicoptero/Helicoptero0.png");
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuerpoGame = new javax.swing.JPanel();
        imagenPrincipal = new javax.swing.JLabel();
        ImagenFondo = new javax.swing.JLabel();
        flechaIzquierda = new javax.swing.JLabel();
        flechaDerecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(14, 77, 144));

        cuerpoGame.setBackground(new java.awt.Color(14, 77, 144));
        cuerpoGame.setMaximumSize(new java.awt.Dimension(720, 450));
        cuerpoGame.setMinimumSize(new java.awt.Dimension(1540, 850));
        cuerpoGame.setPreferredSize(new java.awt.Dimension(1540, 850));
        cuerpoGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Miniaturas/Helicoptero/Helicoptero0.png"))); // NOI18N
        imagenPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cuerpoGame.add(imagenPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 890, 500));

        ImagenFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/fondoImagen.png"))); // NOI18N
        ImagenFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cuerpoGame.add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 1040, 430));

        flechaIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Flecha izquierda.png"))); // NOI18N
        cuerpoGame.add(flechaIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        flechaDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Flecha derecha.png"))); // NOI18N
        cuerpoGame.add(flechaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 300, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuerpoGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuerpoGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGameJP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGameJP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGameJP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGameJP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VistaGameJP().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JPanel cuerpoGame;
    private javax.swing.JLabel flechaDerecha;
    private javax.swing.JLabel flechaIzquierda;
    private javax.swing.JLabel imagenPrincipal;
    // End of variables declaration//GEN-END:variables
}
