/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package launcher;

import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import model.RutaHome;
import org.json.JSONException;
import utilidades.LectorRutaSimulador;
import utilidades.Utility;

/**
 *
 * @author sergio
 */
public final class VistaGame extends javax.swing.JPanel {

    private String imagenPath;
    private ArrayList<String> imagenesSimulador;
    private LectorRutaSimulador rutaSimuladorJson;

    // int x = 0;
    /**
     * Creates new form VistaGameJP2
     */
    public VistaGame() throws JSONException, URISyntaxException {
        LectorRutaSimulador rutaSimuladorJson = new LectorRutaSimulador();
        this.rutaSimuladorJson = rutaSimuladorJson;

        iconosSimulador();
        initComponents();
        selectorGame(1);

    }

    // Selecciona el Preview RutaHome
    public void selectorGame(int botonHome) throws JSONException, URISyntaxException {
        switch (botonHome) {
            case 1:
                imagenPath = imagenesSimulador.get(0);
                break;
            case 2:
                imagenPath = imagenesSimulador.get(1);
                ;
                break;
            case 3:
                imagenPath = imagenesSimulador.get(2);
                ;
                break;
            case 4:
                imagenPath = imagenesSimulador.get(3);
                ;
                break;
            case 5:
                imagenPath = imagenesSimulador.get(4);
                ;
                break;
            case 6:
                imagenPath = imagenesSimulador.get(5);
                ;
                break;

        }
        ImageIcon image = new ImageIcon(imagenPath + "0.png");
        imagenPrincipal.setIcon(image);
        String imagenFondoImg = "src/imagenes/interfazGame/fondoImagen.png";

        Utility utilidades = new Utility();
        imagenFondo.setSize(1050, 430);
        utilidades.SetImageLabel(imagenFondo, imagenFondoImg);
        this.repaint();

        //Inicializar bolitas
        colocarBolitas();
        colocarBolitaLlena();
        colocarTexto(botonHome - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuerpoGame = new javax.swing.JPanel();
        imagenPrincipal = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();
        flechaIzquierda = new javax.swing.JLabel();
        flechaDerecha = new javax.swing.JLabel();
        BolitasPanel = new javax.swing.JPanel();
        bolita1 = new javax.swing.JLabel();
        bolita2 = new javax.swing.JLabel();
        bolita3 = new javax.swing.JLabel();
        bolita4 = new javax.swing.JLabel();
        bolita5 = new javax.swing.JLabel();
        ComenzarBtn = new javax.swing.JLabel();
        descripciónPanel = new javax.swing.JPanel();
        jScrollTexto = new javax.swing.JScrollPane();
        jTextTexto = new javax.swing.JTextArea();
        barraJL = new javax.swing.JLabel();
        jScrollTitulo = new javax.swing.JScrollPane();
        jTTitulo = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(10, 38, 72));
        setMaximumSize(new java.awt.Dimension(1540, 850));
        setMinimumSize(new java.awt.Dimension(1540, 850));
        setPreferredSize(new java.awt.Dimension(1540, 850));

        cuerpoGame.setBackground(new java.awt.Color(10, 38, 72));
        cuerpoGame.setMaximumSize(new java.awt.Dimension(720, 450));
        cuerpoGame.setMinimumSize(new java.awt.Dimension(1540, 850));
        cuerpoGame.setPreferredSize(new java.awt.Dimension(1540, 850));
        cuerpoGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Miniaturas/Helicoptero/Helicoptero0.png"))); // NOI18N
        imagenPrincipal.setText("0");
        cuerpoGame.add(imagenPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 890, 500));

        imagenFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/fondoImagen.png"))); // NOI18N
        imagenFondo.setMaximumSize(new java.awt.Dimension(1050, 430));
        imagenFondo.setMinimumSize(new java.awt.Dimension(1050, 430));
        imagenFondo.setPreferredSize(new java.awt.Dimension(1050, 430));
        cuerpoGame.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 1040, -1));

        flechaIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Flecha izquierda.png"))); // NOI18N
        flechaIzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaIzquierdaMouseClicked(evt);
            }
        });
        cuerpoGame.add(flechaIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        flechaDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Flecha derecha.png"))); // NOI18N
        flechaDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaDerechaMouseClicked(evt);
            }
        });
        cuerpoGame.add(flechaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 300, 40, -1));

        BolitasPanel.setBackground(new java.awt.Color(10, 38, 72));

        bolita1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        bolita2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        bolita3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        bolita4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        bolita5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/PuntoCarruselEmpty.png"))); // NOI18N

        javax.swing.GroupLayout BolitasPanelLayout = new javax.swing.GroupLayout(BolitasPanel);
        BolitasPanel.setLayout(BolitasPanelLayout);
        BolitasPanelLayout.setHorizontalGroup(
            BolitasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BolitasPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(bolita1)
                .addGap(18, 18, 18)
                .addComponent(bolita2)
                .addGap(18, 18, 18)
                .addComponent(bolita3)
                .addGap(18, 18, 18)
                .addComponent(bolita4)
                .addGap(18, 18, 18)
                .addComponent(bolita5)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        BolitasPanelLayout.setVerticalGroup(
            BolitasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BolitasPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(BolitasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bolita1)
                    .addComponent(bolita3)
                    .addComponent(bolita4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bolita5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bolita2))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        cuerpoGame.add(BolitasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 320, 50));

        ComenzarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Comenzar.png"))); // NOI18N
        ComenzarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComenzarBtnMouseClicked(evt);
            }
        });
        cuerpoGame.add(ComenzarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 766, 260, 50));

        descripciónPanel.setBackground(new java.awt.Color(10, 38, 72));
        descripciónPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollTexto.setBorder(null);

        jTextTexto.setEditable(false);
        jTextTexto.setBackground(new java.awt.Color(10, 38, 72));
        jTextTexto.setColumns(20);
        jTextTexto.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jTextTexto.setForeground(new java.awt.Color(255, 255, 255));
        jTextTexto.setLineWrap(true);
        jTextTexto.setRows(5);
        jTextTexto.setText("Texto de prueba");
        jTextTexto.setBorder(null);
        jScrollTexto.setViewportView(jTextTexto);

        descripciónPanel.add(jScrollTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 920, 210));

        barraJL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Barrita aislada descripción.png"))); // NOI18N
        descripciónPanel.add(barraJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 7, -1));

        jScrollTitulo.setBackground(new java.awt.Color(10, 38, 72));
        jScrollTitulo.setBorder(null);
        jScrollTitulo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollTitulo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTTitulo.setEditable(false);
        jTTitulo.setBackground(new java.awt.Color(10, 38, 72));
        jTTitulo.setColumns(20);
        jTTitulo.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        jTTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTTitulo.setRows(5);
        jTTitulo.setText("Título de prueba");
        jTTitulo.setBorder(null);
        jScrollTitulo.setViewportView(jTTitulo);

        descripciónPanel.add(jScrollTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1076, 20));

        cuerpoGame.add(descripciónPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 910, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuerpoGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuerpoGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void flechaDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaDerechaMouseClicked
        setLayout(null);
        // Añadimos el número de imagen en la etiqueta text y recuperamos para sumarle 1, hasta 4
        int x = Integer.parseInt(imagenPrincipal.getText());
        x = x + 1;
        if (x == 5) {
            x = 0;
        }
        // Añadimos numero de imagen y se van cambiando.
        String imagenPrincipalImg = imagenPath + x + ".png";
        imagenPrincipal.setText(String.valueOf(x));
        ImageIcon image = new ImageIcon(imagenPrincipalImg);
        imagenPrincipal.setIcon(image);
        colocarBolitaLlena();
    }//GEN-LAST:event_flechaDerechaMouseClicked

    // Carrusel izquierda
    private void flechaIzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaIzquierdaMouseClicked
        setLayout(null);
        // Añadimos el número de imagen en la etiqueta text y recuperamos para sumarle 1, hasta 4
        int x = Integer.parseInt(imagenPrincipal.getText());
        if (x <= 0) {
            x = 5;
        }
        x = x - 1;
        // Añadimos numero de imagen y se van cambiando.
        String imagenPrincipalImg = imagenPath + x + ".png";
        imagenPrincipal.setText(String.valueOf(x));
        ImageIcon image = new ImageIcon(imagenPrincipalImg);
        imagenPrincipal.setIcon(image);
        colocarBolitaLlena();
    }//GEN-LAST:event_flechaIzquierdaMouseClicked

    private void ComenzarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComenzarBtnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ComenzarBtnMouseClicked

    //Método para bolitas llenas
    public void colocarBolitaLlena() {
        colocarBolitas();
        String imagenBolitaLlena = "src/imagenes/interfazGame/PuntoCarruselFilled.png";
        ImageIcon image2 = new ImageIcon(imagenBolitaLlena);

        int x = Integer.parseInt(imagenPrincipal.getText());

        switch (x) {
            case 0:
                bolita1.setIcon(image2);
                break;
            case 1:
                bolita2.setIcon(image2);
                break;
            case 2:
                bolita3.setIcon(image2);
                break;
            case 3:
                bolita4.setIcon(image2);
                break;
            case 4:
                bolita5.setIcon(image2);
                break;

        }
    }

    //Método para bolitas vacías
    public void colocarBolitas() {
        String imagenBolitaVacia = "src/imagenes/interfazGame/PuntoCarruselEmpty.png";

        ImageIcon image = new ImageIcon(imagenBolitaVacia);
        bolita1.setIcon(image);
        bolita2.setIcon(image);
        bolita3.setIcon(image);
        bolita4.setIcon(image);
        bolita5.setIcon(image);

    }

    public void iconosSimulador() throws JSONException {
        // Recuperamos datos del Json
        ArrayList<String> rutas = rutaSimuladorJson.jsonArray();

        // Creamos Listas para guardar las rutas de las imágenes
        //ArrayList<String> rutasImagenesHome = new ArrayList();
        //String rutaImagenHome = "";
        // Iteramos el Json y añadimos las rutas de las imagenes a una lista
        // for (int x = 0; x <= 6; x++) {
        //JSONArray rutasArray = imagen.getRutaImagenesHome();
        // String numeroSimulador = rutas.get(x).getNumeroSimulador();
        //for (int i = 0; i <= 5; i++) {
        //  rutaImagenHome = rutas.get(x).getRutaImagenes().getString(i);
        // rutasImagenesHome.add(rutaImagenHome);
        // }
        // }
        imagenesSimulador = rutas;

    }

    public void colocarTexto(int botonHome) throws JSONException {
        ArrayList<RutaHome> games = new ArrayList<>();

        //games = lectorJSON.jsonArray();
        //String gameTitulo = games.get(botonHome).getTitulo();
        //String gameDescripcion = games.get(botonHome).getDescripcion();
        //jTTitulo.setText(gameTitulo);
        //jTextTexto.setText(gameDescripcion);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BolitasPanel;
    private javax.swing.JLabel ComenzarBtn;
    private javax.swing.JLabel barraJL;
    private javax.swing.JLabel bolita1;
    private javax.swing.JLabel bolita2;
    private javax.swing.JLabel bolita3;
    private javax.swing.JLabel bolita4;
    private javax.swing.JLabel bolita5;
    private javax.swing.JPanel cuerpoGame;
    private javax.swing.JPanel descripciónPanel;
    private javax.swing.JLabel flechaDerecha;
    private javax.swing.JLabel flechaIzquierda;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel imagenPrincipal;
    private javax.swing.JScrollPane jScrollTexto;
    private javax.swing.JScrollPane jScrollTitulo;
    private javax.swing.JTextArea jTTitulo;
    private javax.swing.JTextArea jTextTexto;
    // End of variables declaration//GEN-END:variables
}
