/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package launcher;

import utilidades.Utility;

/**
 *
 * @author Sergio SM
 */
public class VistaGame1 extends javax.swing.JPanel {

    Utility utilidades = new Utility();

    /**
     * Creates new form VistaGameJP
     */
    public VistaGame1() {
        initComponents();

        utilidades.SetImageLabel(fondoImagen, "src/imagenes/interfazGame/fondoImagen.png");

        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenJl = new javax.swing.JLabel();
        fondoImagen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(14, 77, 144));
        setMinimumSize(new java.awt.Dimension(1540, 850));
        setPreferredSize(new java.awt.Dimension(1540, 850));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenJl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/Miniaturas/Helicoptero/Helicoptero0.png"))); // NOI18N
        add(imagenJl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        fondoImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazGame/fondoImagen.png"))); // NOI18N
        add(fondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1110, 530));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoImagen;
    private javax.swing.JLabel imagenJl;
    // End of variables declaration//GEN-END:variables
}
